#
# Makefile for whole project
#

include Make.public

COM= Share DB Base
#RakNet

EXE=DBServer LoginServer GameServer

SUBDIRS = $(COM) $(EXE)

all : subdirs

subdirs:
	@for i in $(SUBDIRS); do \
	echo    "===>$$i"; \
	(cd $$i && ./rebuild.sh 2>err.log) || exit 1; \
	echo    "<===$$i"; \
done

clean:
	@for i in $(SUBDIRS); do \
	echo    "===>$$i"; \
	(cd $$i && rm -f *.o) || exit 1; \
	echo    "<===$$i"; \
done

